// <auto-generated />
namespace MusicWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialize_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialize_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202105040708501_initialize_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
